#!/bin/bash
#########################
#Programmer: Isaac Kerley
#Date: 9/16/2016
#Purpose: This will start the minecraft server under the current user's home directory then in minecraft then in Server folder.
#########################
#Arrays
#Variables
########Main code########
cd ~/minecraft/Server/ #This changes the current directory to be the current user's home folder then minecraft then Server folder.
echo elua=true>eula.txt
java -Xmx1G -jar minecraft-server.jar -o true #This will start the server
